# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apiyoucefdocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://apiyoucefdocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_770d33d3081c4c049d9cf70435afa0f1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b1200092180455da60dbd6361a1ef23 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: apiyoucefdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_770d33d3081c4c049d9cf70435afa0f1 }}/apiyoucefdocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apiyoucefdocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d079a214f0d4ce88b80e1139800dffa }}
        images: 'apiyoucefdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_770d33d3081c4c049d9cf70435afa0f1 }}/apiyoucefdocker:${{ github.sha }}'